### ISSUE TITLE
[UI] navbar button do not changes color when clicked to go to other page

### ISSUE THREAD

**Issue by codesankalp** [prakharepo/campus_placement_app#5]
while running this project i see a bug that when i click home it is green in colour in navbar but when i click announcements in the navbar i see the colour of announcemnets do not changes which is a issue relate to user interface.

**Comment by codesankalp** [comment]
I will make a pull request to fix this on 1st october as it requires a minor change in template.

**Comment by prakharepo** [comment]
@codesankalp  Thanks for this bug. I have assigned this to you as it is opened by you. Till 1'st October we are looking for what all we can do in one month (Other Issues). We will also contributing along with you so other issues we will assign on 1'st by looking at number of contributor interested. Currently we are busy in deploying it on cloud, so that contributors can see it easily. Thanks for your interest it really means a lot.

**Comment by codesankalp** [comment]
Thanks @prakharepo i'll make a pull request on that day.

**Comment by codesankalp** [comment]
@prakharepo why do you add two urls for one view.
i.e. for home page there is two urls one is localhost:8000/ and other is localhost:8000/index.
should i remove it?

**Comment by prakharepo** [comment]
@codesankalp Yes you can if it will not create other problem. And i have added two urls so i can land on the home page directly by giving localhost:8000/ url.
